version: "3.8"

services:
  immich-server:
    container_name: immich_server
    networks:
      - default
      - proxy_apps
    image: ghcr.io/immich-app/immich-server:v${IMMICH_VERSION}
    devices:
      - ${GPU_PATH:-/dev/dri/card0}:${GPU_PATH:-/dev/dri/card0}
    volumes:
      - upload_data:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - photoprism_app_originals:/mnt/photoprism:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v${IMMICH_VERSION}
    volumes:
      - model_cache:/cache
    env_file:
      - .env
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:7-alpine
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg16-v0.2.1
    labels:
      ofelia.restart: "true"
      ofelia.enabled: "true"
      ofelia.job-exec.immichdbbackup.schedule: "0 0 1 * * *"
      ofelia.job-exec.immichdbbackup.command: "sh -c 'pg_dumpall -U immich -f /var/lib/postgresql/data/backup.sql'"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  proxy_apps:
    name: proxy_apps
    external: true

volumes:
  model_cache:
  db_data:
  upload_data:
  photoprism_app_originals:
    external: true
