x-common-environment: &default-environment
  TZ: Europe/Berlin

x-common-service-config: &default-service-config
  restart: unless-stopped
  environment:
    <<: *default-environment
  security_opt:
    - no-new-privileges:true

services:
  app:
    image: ghcr.io/immich-app/immich-server:release
    <<: *default-service-config
    devices:
      - ${GPU_PATH:-/dev/dri/card0}:${GPU_PATH:-/dev/dri/card0}
    volumes:
      - upload_data:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_USERNAME=immich
      - DB_PASSWORD=immich
      - DB_HOSTNAME=database
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=cache
      - IMMICH_LOG_LEVEL=warn
    depends_on:
      - cache
      - database
    networks:
      - default
      - proxy_apps

  machinelearning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    <<: *default-service-config
    volumes:
      - model_cache:/cache
    environment:
      - DB_USERNAME=immich
      - DB_PASSWORD=immich
      - DB_HOSTNAME=database
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=cache
      - IMMICH_LOG_LEVEL=warn

  cache:
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    <<: *default-service-config
    networks:
      - default

  database:
    image: tensorchord/pgvecto-rs:pg16-v0.2.1
    <<: *default-service-config
    labels:
      - ofelia.restart=true
      - ofelia.enabled=true
      - "ofelia.job-exec.${COMPOSE_PROJECT_NAME}dbbackup.schedule=0 0 1 * * *"
      - "ofelia.job-exec.${COMPOSE_PROJECT_NAME}dbbackup.command=sh -c 'pg_dumpall -U immich -f /var/lib/postgresql/data/backup.sql'"
    environment:
      POSTGRES_PASSWORD: immich
      POSTGRES_USER: immich
      POSTGRES_DB: immich
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  default:
  proxy_apps:
    name: proxy_apps
    external: true

volumes:
  model_cache:
  db_data:
  upload_data:
